const mockAirports = [
    { code: "IST", name: "Istanbul Airport", city: "Istanbul" },
    { code: "JFK", name: "John F. Kennedy International Airport", city: "New York" },
    { code: "LHR", name: "London Heathrow Airport", city: "London" },
    { code: "ADB", name: "İzmir Adnan Menderes Airport", city: "İzmir" },
    { code: "ESB", name: "Ankara Esenboga Airport", city: "Ankara" },
    { code: "AYT", name: "Antalya Airport", city: "Antalya" },
    { code: "ECN", name: "Ercan International Airport", city: "Lefkosa" },
    { code: "DXB", name: "Dubai International Airport", city: "Dubai" },
    { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles" },
    { code: "CUN", name: "CANCUN Airport", city: "Mexico" },
   
  ];
  const mockFlights = [
    {
      id: "1",
      airline: "Turkish Airlines",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "John F. Kennedy International Airport",
      departureCity:"Istanbul",
      arrivalCity:"New York",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "08:00 AM",
      arrivalTime: "09:00 PM",
      flightTime:"6 Hours",
      price: 1800
    },
    {
      id: "2",
      airline: "Turkish Airlines",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "John F. Kennedy International Airport",
      departureCity:"Istanbul",
      arrivalCity:"New York",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "09:00 AM",
      arrivalTime: "05:00 PM",
      flightTime:"4 Hours",
      price: 1500,
    },
    {
      id: "3",
      airline: "British Airways",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "John F. Kennedy International Airport",
      departureCity:"Istanbul",
      arrivalCity:"New York",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"7 Hours",
      price: 500,
    },
    {
      id: "4",
      airline: "British Airways",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "John F. Kennedy International Airport",
      departureCity:"Istanbul",
      arrivalCity:"New York",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "12:30 AM",
      arrivalTime: "01:00 AM",
      flightTime:"4 Hours",
      price: 1100,
    },
    {
      id: "5",
      airline: "Turkish Airways",
      departureAirport: "İzmir Adnan Menderes Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"Izmir",
      arrivalCity:"London",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"2 Hours",
      price: 850,
    },
    {
      id: "6",
      airline: "Turkish Airlines",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "Ercan International Airport",
      departureCity:"Istanbul",
      arrivalCity:"Lefkosa",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"4 Hours",
      price: 700,
    },
    {
      id: "7",
      airline: "British Airways",
      departureAirport: "Antalya Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"Antalya",
      arrivalCity:"London",
      departureDate:"2023-10-12",
      arrivalDate:"2023-10-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 900,
    },
    {
      id: "8",
      airline: "Turkish Airlines",
      departureAirport: "Ankara Esenboga Airport",
      arrivalAirport: "Antalya Airport",
      departureCity:"Ankara",
      arrivalCity:"Antalya",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1200,
    },
    {
      id: "9",
      airline: "British Airways",
      departureAirport: "Dubai International Airport",
      arrivalAirport: "İzmir Adnan Menderes Airport",
      departureCity:"Dubai",
      arrivalCity:"İzmir",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1300,
    },
    {
      id: "10",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "11",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "12",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "13",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "14",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "15",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "16",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "17",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "18",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "19",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "20",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "21",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "22",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "23",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"New York",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1100,
    },
    {
      id: "24",
      airline: "British Airways",
      departureAirport: "Ankara Esenboga Airport",
      arrivalAirport: "Istanbul Airport",
      departureCity:"Ankara",
      arrivalCity:"Istanbul",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1200,
    },
    {
      id: "25",
      airline: "British Airways",
      departureAirport: "Antalya Airport",
      arrivalAirport: "Dubai International Airport",
      departureCity:"Antalya",
      arrivalCity:"Dubai",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 1000,
    },
    {
      id: "26",
      airline: "Turkish Airlines",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "Ercan International Airport",
      departureCity:"Istanbul",
      arrivalCity:"Lefkosa",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 300,
    },
    {
      id: "27",
      airline: "British Airways",
      departureAirport: "Istanbul Airport",
      arrivalAirport: "Antalya Airport",
      departureCity:"Istanbul",
      arrivalCity:"Antalya",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 400,
    },
    {
      id: "28",
      airline: "British Airways",
      departureAirport: "CANCUN Airport",
      arrivalAirport: "London Heathrow Airport",
      departureCity:"Mexico",
      arrivalCity:"London",
      departureDate:"2023-11-12",
      arrivalDate:"2023-11-12",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"6 Hours",
      price: 500,
    },
    {
      id: "29",
      airline: "British Airways",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "Istanbul Airport",
      departureCity:"New York",
      arrivalCity:"Istanbul",
      departureDate:"2023-10-13",
      arrivalDate:"2023-10-13",
      departureTime: "10:30 AM",
      arrivalTime: "01:00 PM",
      flightTime:"5 Hours",
      price: 800,
    },
    {
      id: "30",
      airline: "Turkish Airlines",
      departureAirport: "John F. Kennedy International Airport",
      arrivalAirport: "Istanbul Airport",
      departureCity:"New York",
      arrivalCity:"Istanbul",
      departureDate:"2023-10-13",
      arrivalDate:"2023-10-13",
      departureTime: "13:30 AM",
      arrivalTime: "04:00 PM",
      flightTime:"6 Hours",
      price: 1200,
    },
  
];

  
  const fetchFlights = async (searchParams) => {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1000));
    return mockFlights;
  };
  
  export { mockAirports, mockFlights, fetchFlights };
  